name = "pdf-pipeline-pro"
main = "src/worker.js"
compatibility_date = "2025-01-01"

[[r2_buckets]]
binding = "RAW_BUCKET"
bucket_name = "raw-pdf"

[[r2_buckets]]
binding = "FINAL_BUCKET"
bucket_name = "encrypted-pdf"

[[queues.producers]]
queue = "pdf-jobs"
binding = "PDF_QUEUE"

[[queues.consumers]]
queue = "pdf-jobs"
max_batch_size = 10

[vars]

[[containers]]
class_name = "PDF_ENCRYPTOR"
image = "./container/Dockerfile"
